package modelo;

import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String departamento;
	private Set notases = new HashSet(0);

	public Asignaturas() {
	}

	public Asignaturas(String nombre, String departamento) {
		this.nombre = nombre;
		this.departamento = departamento;
	}

	public Asignaturas(String nombre, String departamento, Set notases) {
		this.nombre = nombre;
		this.departamento = departamento;
		this.notases = notases;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public Set getNotases() {
		return this.notases;
	}

	public void setNotases(Set notases) {
		this.notases = notases;
	}

}
