package modelo;

// Generated 06-jun-2017 9:54:14 by Hibernate Tools 5.2.0.CR1

/**
 * Actores generated by hbm2java
 */
public class Actores implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String FNacimiento;
	private String nacionalidad;

	public Actores() {
	}

	public Actores(String nombre, String FNacimiento, String nacionalidad) {
		this.nombre = nombre;
		this.FNacimiento = FNacimiento;
		this.nacionalidad = nacionalidad;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFNacimiento() {
		return this.FNacimiento;
	}

	public void setFNacimiento(String FNacimiento) {
		this.FNacimiento = FNacimiento;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}
	

}
