package modelo;
// Generated 06-jun-2017 9:54:14 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

	private Integer codigo;
	private String titulo;
	private Date fecha;
	private double presupuesto;

	public Peliculas() {
	}

	public Peliculas(String titulo, Date fecha, double presupuesto) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

}
