package modelo;
// Generated 06-jun-2017 9:54:14 by Hibernate Tools 5.2.0.CR1

/**
 * Reparto generated by hbm2java
 */
public class Reparto implements java.io.Serializable {

	private Integer codigo;
	private Integer CActor;
	private Integer CPelicula;

	public Reparto() {
	}

	public Reparto(Integer CActor, Integer CPelicula) {
		this.CActor = CActor;
		this.CPelicula = CPelicula;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Integer getCActor() {
		return this.CActor;
	}

	public void setCActor(Integer CActor) {
		this.CActor = CActor;
	}

	public Integer getCPelicula() {
		return this.CPelicula;
	}

	public void setCPelicula(Integer CPelicula) {
		this.CPelicula = CPelicula;
	}

}
